`timescale 1ns / 1ps

//-----------------------------------------------------------------------------
// Module Name : TB
// Description :
//   Testbench for verifying the operation of the Sawtooth Generator and
//   FIR Filter modules.
//
// Functionality :
//   1. Generates a periodic clock signal with a period of 10 ns.
//   2. Instantiates the Sawtooth_Generator module to produce an 8-bit
//      sawtooth waveform.
//   3. Applies the generated sawtooth waveform as the input to the
//      FIR_Filter module.
//   4. Observes the filtered output waveform to verify the FIR filter
//      response and smoothing effect on the sawtooth signal.
//
// Simulation Setup :
//   - Clock period : 10 ns
//   - Clock frequency : 100 MHz
//   - Input signal : 8-bit digital sawtooth waveform
//   - Output signal : Filtered waveform generated by the FIR filter
//
// Signals :
//   clk          - System clock generated by the testbench.
//   sawtooth_out - Output of the Sawtooth Generator.
//   filter_out   - Output of the FIR Filter.
//
//-----------------------------------------------------------------------------

module TB();

reg clk = 0;

// Generate a 100 MHz clock signal
// Clock toggles every 5 ns, resulting in a 10 ns period.
always begin
    #5 clk = ~clk;
end

// Interconnecting signals between modules
wire [7:0] sawtooth_out;
wire [7:0] filter_out;

// Instantiate the sawtooth waveform generator
Sawtooth_Generator Gen(
    .clk(clk),
    .sawtooth(sawtooth_out)
);

// Instantiate the FIR filter and connect the
// sawtooth waveform as its input signal
FIR_Filter Fil(
    .clk(clk),
    .x(sawtooth_out),
    .y(filter_out)
);

endmodule
